# RetailPulse: Data Quality Assessment

## Overview

This notebook examines the quality and consistency of the dataset, focusing on missing values, duplicate records, data types, and categorical inconsistencies.

## Objectives

* Assess the dataset's completeness and consistency.
* Investigate missing values and duplicate records.
* Examine individual columns for potential data quality issues.
* Identify inconsistencies that may require attention during data cleaning.

## 1. Load the Dataset

The raw Amazon Sale Report dataset is loaded into a Pandas DataFrame to begin the data quality assessment.

In [73]:
import pandas as pd

csv_file = "../data/raw/Amazon Sale Report.csv"

df = pd.read_csv(csv_file)

print("DataFrame created successfully!")

DataFrame created successfully!

C:\Users\praya\AppData\Local\Temp\ipykernel_14496\3374428460.py:5: DtypeWarning: Columns (23: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)

## 2. Dataset Dimensions

The dataset contains **128,975 rows and 24 columns**, representing the overall size of the data being assessed.

In [74]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 128975
Columns: 24

## 3. Column Names and Data Types

This section lists the dataset's columns and their data types to provide an overview of the available fields and how their values are represented.

In [75]:
columns = pd.DataFrame({
    'Column': df.columns.tolist()
})

columns

                Column
0                index
1             Order ID
2                 Date
3               Status
4           Fulfilment
5       Sales Channel
6   ship-service-level
7                Style
8                  SKU
9             Category
10                Size
11                ASIN
12      Courier Status
13                 Qty
14            currency
15              Amount
16           ship-city
17          ship-state
18    ship-postal-code
19        ship-country
20       promotion-ids
21                 B2B
22        fulfilled-by
23         Unnamed: 22

In [76]:
datatypes = pd.DataFrame({
    'Column': df.columns,
    'Data Type': df.dtypes.astype(str).values
})

datatypes

                Column Data Type
0                index     int64
1             Order ID       str
2                 Date       str
3               Status       str
4           Fulfilment       str
5       Sales Channel        str
6   ship-service-level       str
7                Style       str
8                  SKU       str
9             Category       str
10                Size       str
11                ASIN       str
12      Courier Status       str
13                 Qty     int64
14            currency       str
15              Amount   float64
16           ship-city       str
17          ship-state       str
18    ship-postal-code   float64
19        ship-country       str
20       promotion-ids       str
21                 B2B      bool
22        fulfilled-by       str
23         Unnamed: 22    object

## 4. Dataset Preview

The first and last records, along with a random sample, provide an initial view of the dataset's contents and record structure.

In [77]:
df.head(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
5,5,404-1490984-4578765,04-30-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.00,GHAZIABAD,UTTAR PRADESH,201102.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
6,6,408-5748499-6859555,04-30-22,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,...,INR,653.00,CHANDIGARH,CHANDIGARH,160036.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
7,7,406-7807733-3785945,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,...,INR,399.00,HYDERABAD,TELANGANA,500032.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,...,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
9,9,402-4393761-0311520,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,...,INR,363.00,Chennai,TAMIL NADU,600041.0,IN,NaN,False,NaN,NaN

In [78]:
df.tail(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
128965,128965,408-5154281-4593912,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,J0119,J0119-TP-XXXL,Top,...,INR,574.0,Prayagraj (ALLAHABAD),UTTAR PRADESH,211007.0,IN,NaN,False,NaN,False
128966,128966,406-9812666-2474761,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET224,SET224-KR-NP-XS,Set,...,INR,1132.0,CHENNAI 600042,TAMIL NADU,600042.0,IN,NaN,False,NaN,False
128967,128967,404-5182288-1653947,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,...,NaN,NaN,Kolkata,WEST BENGAL,700040.0,IN,NaN,False,NaN,False
128968,128968,403-7059995-7618722,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,...,INR,824.0,Delhi,DELHI,110053.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128969,128969,404-3802633-7250760,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,SET044,SET044-KR-NP-M,Set,...,INR,612.0,MUMBAI,MAHARASHTRA,400017.0,IN,NaN,False,NaN,False
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.0,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.0,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.0,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.0,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.0,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [79]:
df.sample(10)

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
76007,76007,402-1048570-1182758,05-09-22,Shipped,Amazon,Amazon.in,Expedited,JNE3560,JNE3560-KR-M,kurta,...,INR,544.0,SURAT,Gujarat,395007.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
96539,96539,171-8216457-9769115,06-24-22,Shipped,Amazon,Amazon.in,Expedited,NW006,NW006-ST-SR-XS,Set,...,INR,496.0,KANPUR,UTTAR PRADESH,208011.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
77968,77968,403-8751192-3620347,05-08-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3798,JNE3798-KR-XXXL,Western Dress,...,INR,725.0,THIRUVANANTHAPURAM,KERALA,695584.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
72384,72384,404-6535434-7093135,05-13-22,Cancelled,Merchant,Amazon.in,Standard,JNE3608,JNE3608-KR-L,kurta,...,INR,341.9,THANE,MAHARASHTRA,400709.0,IN,NaN,False,Easy Ship,False
15063,15063,406-0426318-8049926,04-21-22,Shipped,Amazon,Amazon.in,Expedited,JNE3399,JNE3399-KR-S,kurta,...,INR,435.0,GUDIVADA KRISHNA DISTRICT,ANDHRA PRADESH,521301.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
57594,57594,408-9585605-1508314,05-25-22,Shipped,Amazon,Amazon.in,Expedited,J0341,J0341-DR-L,Western Dress,...,INR,885.0,AGRA,UTTAR PRADESH,282002.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
127450,127450,405-3542566-1414734,06-01-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-M,Western Dress,...,INR,659.0,MUMBAI,MAHARASHTRA,400074.0,IN,NaN,False,NaN,False
48463,48463,405-8570690-2409915,04-01-22,Shipped,Amazon,Amazon.in,Expedited,BTM047,BTM047-PP-L,Bottom,...,INR,360.0,SALASAR,RAJASTHAN,331506.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,NaN
123886,123886,407-9850146-6739504,06-04-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3399,JNE3399-KR-S,kurta,...,NaN,NaN,PANMANA,KERALA,691583.0,IN,NaN,False,NaN,False
55602,55602,403-6397402-4926715,05-26-22,Shipped,Amazon,Amazon.in,Expedited,PJNE2014,PJNE2014-KR-N-6XL,kurta,...,INR,798.0,KOZHIKODE,KERALA,673032.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

## 5. Dataset Structure

The dataset structure provides details about column data types, non-null values, and memory usage, helping identify potential data quality concerns.

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(1), str(18)
memory usage: 22.8+ MB

## 6. Descriptive Statistics

This section provides summary statistics for numerical columns, including measures of central tendency, spread, and range.

In [81]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

## 7. Duplicate Records

This section checks for exact duplicate rows to assess whether the dataset contains repeated records that may affect the analysis.

In [82]:
print("Exact duplicated rows:", df.duplicated().sum())

Exact duplicated rows: 0

In [83]:
print("Exact duplicated Order IDs:", df["Order ID"].duplicated().sum())

Exact duplicated Order IDs: 8597

## 8. Missing Values

This section examines missing values across the dataset to assess data completeness and identify columns that may require attention during data cleaning.

In [84]:
missing_values = pd.DataFrame({
    'Column': df.columns,
    'Missing Values': df.isna().sum().astype(int).values,
    "Missing Percentage": (df.isna().mean() * 100).round(2).astype(float).values
})

missing_values.sort_values(by="Missing Percentage", ascending=False, inplace=True)

missing_values

                Column  Missing Values  Missing Percentage
22        fulfilled-by           89698               69.55
20       promotion-ids           49153               38.11
23         Unnamed: 22           49050               38.03
14            currency            7795                6.04
15              Amount            7795                6.04
12      Courier Status            6872                5.33
19        ship-country              33                0.03
16           ship-city              33                0.03
17          ship-state              33                0.03
18    ship-postal-code              33                0.03
5       Sales Channel                0                0.00
4           Fulfilment               0                0.00
3               Status               0                0.00
2                 Date               0                0.00
1             Order ID               0                0.00
0                index               0                0.00
7                Style               0                0.00
6   ship-service-level               0                0.00
13                 Qty               0                0.00
11                ASIN               0                0.00
8                  SKU               0                0.00
9             Category               0                0.00
10                Size               0                0.00
21                 B2B               0                0.00

## 9. Unique Values

This section examines the number of unique values in each column to understand categorical diversity and identify fields that may require further investigation.

In [85]:
unique_values = pd.DataFrame({
    'Column': df.columns,
    'Unique Values': df.nunique().astype(int).values
    
})

unique_values

                Column  Unique Values
0                index         128975
1             Order ID         120378
2                 Date             91
3               Status             13
4           Fulfilment              2
5       Sales Channel               2
6   ship-service-level              2
7                Style           1377
8                  SKU           7195
9             Category              9
10                Size             11
11                ASIN           7190
12      Courier Status              3
13                 Qty             10
14            currency              1
15              Amount           1410
16           ship-city           8955
17          ship-state             69
18    ship-postal-code           9459
19        ship-country              1
20       promotion-ids           5787
21                 B2B              2
22        fulfilled-by              1
23         Unnamed: 22              1

## 10. Date Overview

This section examines the date range, number of unique dates, and missing date values to understand the temporal coverage of the dataset.

In [86]:
date_summary = pd.DataFrame({
    "Fields": [
        "Unique Dates",
        "Missing Dates",
        "Latest Date",
        "Earliest Date"
    ],
    "Value": [
        df["Date"].nunique(),
        df["Date"].isna().sum(),
        df["Date"].max(),
        df["Date"].min()
    ]
    
})

date_summary

          Fields     Value
0   Unique Dates        91
1  Missing Dates         0
2    Latest Date  06-29-22
3  Earliest Date  03-31-22

In [87]:
pd.DataFrame({
    "Date Consistency": df["Date"].sample(10).tolist()
})

  Date Consistency
0         04-05-22
1         04-10-22
2         06-03-22
3         05-17-22
4         05-07-22
5         05-26-22
6         06-04-22
7         05-26-22
8         06-05-22
9         04-20-22

## 11. Index Column Inspection

This section examines the `index` column to assess its data type, completeness, uniqueness, and potential duplicate values.

In [88]:
index_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values",
        "Minimum Value",
        "Maximum Value",
        "Duplicated Values",
        "Sequential from Zero",
        "Matches DataFrame Row Positions"
    ],
    "Value": [
        "index",
        str(df["index"].dtype),
        len(df["index"]),
        df["index"].isna().sum(),
        df["index"].nunique(),
        df["index"].min(),
        df["index"].max(),
        df["index"].duplicated().sum(),
        df["index"].is_monotonic_increasing and df["index"].iloc[0] == 0,
        df["index"].reset_index(drop=True).equals(
            pd.Series(range(len(df)), name="index")
        )
    ]
})

index_inspection

                            Fields   Value
0                      Column Name   index
1                        Data Type   int64
2                       Total Rows  128975
3                   Missing Values       0
4                    Unique Values  128975
5                    Minimum Value       0
6                    Maximum Value  128974
7                Duplicated Values       0
8             Sequential from Zero    True
9  Matches DataFrame Row Positions    True

## 12. Order ID Inspection

This section examines the `Order ID` column's data type, completeness, uniqueness, and repeated values to understand how order identifiers are represented across the dataset.

In [89]:
order_id_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Order IDs",
        "Duplicated ID Occurrences",
        "Orders Appearing More Than Once",
        "Maximum Rows per Order"
    ],
    "Value": [
        "Order ID",
        str(df["Order ID"].dtype),
        len(df["Order ID"]),
        df["Order ID"].isna().sum(),
        df["Order ID"].nunique(),
        df["Order ID"].duplicated().sum(),
        df["Order ID"].value_counts().gt(1).sum(),
        df["Order ID"].value_counts().max()
    ]
})

order_id_inspection

                            Fields     Value
0                      Column Name  Order ID
1                        Data Type       str
2                       Total Rows    128975
3                   Missing Values         0
4                 Unique Order IDs    120378
5        Duplicated ID Occurrences      8597
6  Orders Appearing More Than Once      6846
7           Maximum Rows per Order        12

## 13. Date Column Inspection

This section examines the `Date` column's data type, completeness, and date range to assess its suitability for subsequent analysis.

In [90]:
date_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Dates",
        "Date Format Examples",
        "Earliest Date",
        "Latest Date",
        "Invalid Dates"
    ],
    "Value": [
        "Date",
        str(df["Date"].dtype),
        len(df["Date"]),
        df["Date"].isna().sum(),
        df["Date"].nunique(),
        df["Date"].dropna().sample(min(10, df["Date"].notna().sum())).tolist(),
        pd.to_datetime(df["Date"], format="%m-%d-%y", errors="coerce").min(),
        pd.to_datetime(df["Date"], format="%m-%d-%y", errors="coerce").max(),
        pd.to_datetime(df["Date"], format="%m-%d-%y", errors="coerce").isna().sum()
    ]
})

date_inspection

                 Fields                                              Value
0           Column Name                                               Date
1             Data Type                                                str
2            Total Rows                                             128975
3        Missing Values                                                  0
4          Unique Dates                                                 91
5  Date Format Examples  [06-16-22, 06-24-22, 04-02-22, 04-15-22, 04-30...
6         Earliest Date                                2022-03-31 00:00:00
7           Latest Date                                2022-06-29 00:00:00
8         Invalid Dates                                                  0

## 14. Status Column Inspection

This section examines the `Status` column's data type, completeness, and distinct values to understand the different order statuses recorded in the dataset.

In [91]:
status_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Statuses"
    ],
    "Value": [
        "Status",
        str(df["Status"].dtype),
        len(df["Status"]),
        df["Status"].isna().sum(),
        df["Status"].nunique()
    ]
})

status_inspection

            Fields   Value
0      Column Name  Status
1        Data Type     str
2       Total Rows  128975
3   Missing Values       0
4  Unique Statuses      13

In [92]:
df["Status"].value_counts(dropna=False).to_frame("Count")

                               Count
Status
Shipped                        77804
Shipped - Delivered to Buyer   28769
Cancelled                      18332
Shipped - Returned to Seller    1953
Shipped - Picked Up              973
Pending                          658
Pending - Waiting for Pick Up    281
Shipped - Returning to Seller    145
Shipped - Out for Delivery        35
Shipped - Rejected by Buyer       11
Shipping                           8
Shipped - Lost in Transit          5
Shipped - Damaged                  1

## 15. Fulfilment Column Inspection

This section examines the `Fulfilment` column's data type, completeness, and distinct values to understand how orders are fulfilled.

In [93]:
fulfilment_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values"
    ],
    "Value": [
        "Fulfilment",
        str(df["Fulfilment"].dtype),
        len(df["Fulfilment"]),
        df["Fulfilment"].isna().sum(),
        df["Fulfilment"].nunique()
    ]
})

fulfilment_inspection

           Fields       Value
0     Column Name  Fulfilment
1       Data Type         str
2      Total Rows      128975
3  Missing Values           0
4   Unique Values           2

In [94]:
df["Fulfilment"].value_counts(dropna=False).to_frame("Count")

            Count
Fulfilment
Amazon      89698
Merchant    39277

## 16. Sales Channel Inspection

This section examines the `Sales Channel` column's data type, completeness, and distinct values to understand the channels through which orders are recorded.

In [95]:
sales_channel_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values"
    ],
    "Value": [
        "Sales Channel ",
        str(df["Sales Channel "].dtype),
        len(df["Sales Channel "]),
        df["Sales Channel "].isna().sum(),
        df["Sales Channel "].nunique()
    ]
})

sales_channel_inspection

           Fields           Value
0     Column Name  Sales Channel
1       Data Type             str
2      Total Rows          128975
3  Missing Values               0
4   Unique Values               2

In [96]:
df["Sales Channel "].value_counts(dropna=False).to_frame("Count")

                 Count
Sales Channel
Amazon.in       128851
Non-Amazon         124

## 17. Shipping Service Level Inspection

This section examines the `ship-service-level` column's data type, completeness, and distinct values to understand the shipping service levels recorded in the dataset.

In [97]:
ship_service_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values"
    ],
    "Value": [
        "ship-service-level",
        str(df["ship-service-level"].dtype),
        len(df["ship-service-level"]),
        df["ship-service-level"].isna().sum(),
        df["ship-service-level"].nunique()
    ]
})

ship_service_inspection

           Fields               Value
0     Column Name  ship-service-level
1       Data Type                 str
2      Total Rows              128975
3  Missing Values                   0
4   Unique Values                   2

In [98]:
df["ship-service-level"].value_counts(dropna=False).to_frame("Count")

                    Count
ship-service-level
Expedited           88615
Standard            40360

## 18. Style Column Inspection

This section examines the `Style` column's data type, completeness, unique values, and repeated occurrences to understand how product styles are represented in the dataset.

In [99]:
style_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values",
        "Duplicated Value Occurrences"
    ],
    "Value": [
        "Style",
        str(df["Style"].dtype),
        len(df["Style"]),
        df["Style"].isna().sum(),
        df["Style"].nunique(),
        df["Style"].duplicated().sum()
    ]
})

style_inspection

                         Fields   Value
0                   Column Name   Style
1                     Data Type     str
2                    Total Rows  128975
3                Missing Values       0
4                 Unique Values    1377
5  Duplicated Value Occurrences  127598

In [100]:
df["Style"].value_counts(dropna=False).head(10).to_frame("Count")

         Count
Style
JNE3797   4224
JNE3405   2263
J0230     1868
SET268    1860
J0341     1630
J0003     1627
SET324    1284
SET345    1250
JNE3373   1173
JNE3440   1054

## 19. SKU Column Inspection

This section examines the `SKU` column's data type, completeness, unique values, and repeated occurrences to understand how individual product identifiers are represented in the dataset.

In [101]:
sku_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values",
        "Duplicated Value Occurrences"
    ],
    "Value": [
        "SKU",
        str(df["SKU"].dtype),
        len(df["SKU"]),
        df["SKU"].isna().sum(),
        df["SKU"].nunique(),
        df["SKU"].duplicated().sum()
    ]
})

sku_inspection

                         Fields   Value
0                   Column Name     SKU
1                     Data Type     str
2                    Total Rows  128975
3                Missing Values       0
4                 Unique Values    7195
5  Duplicated Value Occurrences  121780

In [102]:
df["SKU"].value_counts(dropna=False).head(10).to_frame("Count")

                Count
SKU
JNE3797-KR-L      773
JNE3797-KR-M      657
JNE3797-KR-S      587
JNE3405-KR-L      535
J0230-SKD-M       507
JNE3797-KR-XL     474
J0230-SKD-S       452
JNE3405-KR-S      443
JNE3797-KR-XS     431
JNE3797-KR-XXL    395

## 20. Category Column Inspection

This section examines the `Category` column's data type, completeness, and distinct values to understand the product categories represented in the dataset.

In [103]:
category_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values"
    ],
    "Value": [
        "Category",
        str(df["Category"].dtype),
        len(df["Category"]),
        df["Category"].isna().sum(),
        df["Category"].nunique()
    ]
})

category_inspection

           Fields     Value
0     Column Name  Category
1       Data Type       str
2      Total Rows    128975
3  Missing Values         0
4   Unique Values         9

In [104]:
df["Category"].value_counts(dropna=False).to_frame("Count")

               Count
Category
Set            50284
kurta          49877
Western Dress  15500
Top            10622
Ethnic Dress    1159
Blouse           926
Bottom           440
Saree            164
Dupatta            3

## 21. Size Column Inspection

This section examines the `Size` column's data type, completeness, and distinct values to understand the product sizes represented in the dataset.

In [105]:
size_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values"
    ],
    "Value": [
        "Size",
        str(df["Size"].dtype),
        len(df["Size"]),
        df["Size"].isna().sum(),
        df["Size"].nunique()
    ]
})

size_inspection

           Fields   Value
0     Column Name    Size
1       Data Type     str
2      Total Rows  128975
3  Missing Values       0
4   Unique Values      11

In [106]:
df["Size"].value_counts(dropna=False).to_frame("Count")

      Count
Size
M     22711
L     22132
XL    20876
XXL   18096
S     17090
3XL   14816
XS    11161
6XL     738
5XL     550
4XL     427
Free    378

## 22. ASIN Column Inspection

This section examines the `ASIN` column's data type, completeness, unique values, and repeated occurrences to understand how Amazon Standard Identification Numbers are represented in the dataset.

In [107]:
asin_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values",
        "Duplicated Value Occurrences"
    ],
    "Value": [
        "ASIN",
        str(df["ASIN"].dtype),
        len(df["ASIN"]),
        df["ASIN"].isna().sum(),
        df["ASIN"].nunique(),
        df["ASIN"].duplicated().sum()
    ]
})

asin_inspection

                         Fields   Value
0                   Column Name    ASIN
1                     Data Type     str
2                    Total Rows  128975
3                Missing Values       0
4                 Unique Values    7190
5  Duplicated Value Occurrences  121785

In [108]:
df["ASIN"].value_counts(dropna=False).head(10).to_frame("Count")

            Count
ASIN
B09SDXFFQ1    773
B09SDY8DCT    657
B09SDYQ3WG    587
B081WSCKPQ    535
B08XNJG8B1    507
B09SDXRYBG    474
B08XNJ19QH    452
B081WX4G4Q    443
B09SDY9SQ6    431
B09SDXSQ33    395

## 23. Courier Status Inspection

This section examines the `Courier Status` column's data type, completeness, and distinct values to understand the delivery statuses recorded by the courier.

In [109]:
courier_status_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values"
    ],
    "Value": [
        "Courier Status",
        str(df["Courier Status"].dtype),
        len(df["Courier Status"]),
        df["Courier Status"].isna().sum(),
        df["Courier Status"].nunique()
    ]
})

courier_status_inspection

           Fields           Value
0     Column Name  Courier Status
1       Data Type             str
2      Total Rows          128975
3  Missing Values            6872
4   Unique Values               3

In [110]:
df["Courier Status"].value_counts(dropna=False).to_frame("Count")

                 Count
Courier Status
Shipped         109487
NaN               6872
Unshipped         6681
Cancelled         5935

## 24. Quantity Column Inspection

This section examines the `Qty` column's data type, completeness, and distribution of recorded quantities to identify unusual values that may require further investigation.

In [111]:
qty_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values",
        "Minimum Value",
        "Maximum Value",
        "Mean",
        "Median",
        "Zero Values",
        "Negative Values"
    ],
    "Value": [
        "Qty",
        str(df["Qty"].dtype),
        len(df["Qty"]),
        df["Qty"].isna().sum(),
        df["Qty"].nunique(),
        df["Qty"].min(),
        df["Qty"].max(),
        round(df["Qty"].mean(), 2),
        df["Qty"].median(),
        df["Qty"].eq(0).sum(),
        df["Qty"].lt(0).sum()
    ]
})

qty_inspection

             Fields   Value
0       Column Name     Qty
1         Data Type   int64
2        Total Rows  128975
3    Missing Values       0
4     Unique Values      10
5     Minimum Value       0
6     Maximum Value      15
7              Mean     0.9
8            Median     1.0
9       Zero Values   12807
10  Negative Values       0

In [112]:
df["Qty"].value_counts(dropna=False).sort_index().to_frame("Count")

      Count
Qty
0     12807
1    115780
2       341
3        32
4         9
5         2
8         1
9         1
13        1
15        1

In [113]:
df.loc[df["Qty"].eq(0), "Status"].value_counts().to_frame("Count")

                              Count
Status
Cancelled                     12701
Shipped                          93
Shipped - Delivered to Buyer      8
Shipped - Returned to Seller      3
Pending                           2

## 25. Currency Column Inspection

This section examines the `currency` column's data type, completeness, and distinct values to understand the currency recorded for sales transactions.

In [114]:
currency_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values"
    ],
    "Value": [
        "currency",
        str(df["currency"].dtype),
        len(df["currency"]),
        df["currency"].isna().sum(),
        f"{df['currency'].isna().mean() * 100:.2f}%",
        df["currency"].nunique()
    ]
})

currency_inspection

               Fields     Value
0         Column Name  currency
1           Data Type       str
2          Total Rows    128975
3      Missing Values      7795
4  Missing Percentage     6.04%
5       Unique Values         1

In [115]:
df["currency"].value_counts(dropna=False).to_frame("Count")

           Count
currency
INR       121180
NaN         7795

## 26. Amount Column Inspection

This section examines the `Amount` column's data type, completeness, and value distribution to identify missing, zero, or unusual amounts that may require further investigation.

In [116]:
amount_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values",
        "Minimum Value",
        "Maximum Value",
        "Mean",
        "Median",
        "Zero Values",
        "Negative Values"
    ],
    "Value": [
        "Amount",
        str(df["Amount"].dtype),
        len(df["Amount"]),
        df["Amount"].isna().sum(),
        f"{df['Amount'].isna().mean() * 100:.2f}%",
        df["Amount"].nunique(),
        df["Amount"].min(),
        df["Amount"].max(),
        round(df["Amount"].mean(), 2),
        df["Amount"].median(),
        df["Amount"].eq(0).sum(),
        df["Amount"].lt(0).sum()
    ]
})

amount_inspection

                Fields    Value
0          Column Name   Amount
1            Data Type  float64
2           Total Rows   128975
3       Missing Values     7795
4   Missing Percentage    6.04%
5        Unique Values     1410
6        Minimum Value      0.0
7        Maximum Value   5584.0
8                 Mean   648.56
9               Median    605.0
10         Zero Values     2343
11     Negative Values        0

In [117]:
df["Amount"].value_counts(dropna=False).head(10).to_frame("Count")

        Count
Amount
NaN      7795
399.0    5442
771.0    2797
735.0    2436
0.0      2343
487.0    2293
788.0    1969
301.0    1865
376.0    1810
635.0    1787

In [118]:
df["Amount"].describe()

count    121180.000000
mean        648.561465
std         281.211687
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: Amount, dtype: float64

In [119]:
df.loc[df["Amount"].eq(0), "Status"].value_counts().to_frame("Count")

                               Count
Status
Shipped                         1518
Shipped - Delivered to Buyer     716
Shipped - Returned to Seller      51
Shipped - Picked Up               28
Pending                           17
Pending - Waiting for Pick Up      9
Shipped - Lost in Transit          2
Shipped - Returning to Seller      2

## 27. Shipping City Inspection

This section examines the `ship-city` column's data type, completeness, and frequently occurring values to understand the distribution of shipping destinations and identify potential inconsistencies in city names.

In [120]:
ship_city_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values"
    ],
    "Value": [
        "ship-city",
        str(df["ship-city"].dtype),
        len(df["ship-city"]),
        df["ship-city"].isna().sum(),
        f"{df['ship-city'].isna().mean() * 100:.2f}%",
        df["ship-city"].nunique()
    ]
})

ship_city_inspection

               Fields      Value
0         Column Name  ship-city
1           Data Type        str
2          Total Rows     128975
3      Missing Values         33
4  Missing Percentage      0.03%
5       Unique Values       8955

In [121]:
df["ship-city"].value_counts(dropna=False).head(15).to_frame("Count")

             Count
ship-city
BENGALURU    11217
HYDERABAD     8074
MUMBAI        6126
NEW DELHI     5795
CHENNAI       5421
PUNE          3857
KOLKATA       2381
GURUGRAM      1868
THANE         1701
LUCKNOW       1458
NOIDA         1419
GHAZIABAD     1328
NAVI MUMBAI   1263
AHMEDABAD     1236
JAIPUR         948

In [122]:
city_names = df["ship-city"].dropna()

city_consistency = pd.DataFrame({
    "Fields": [
        "Unique City Names",
        "Names with Leading/Trailing Whitespace",
        "Names with Inconsistent Capitalization",
        "Unique Names After Trimming Whitespace",
        "Unique Names After Standardizing Case"
    ],
    "Value": [
        city_names.nunique(),
        city_names.ne(city_names.str.strip()).sum(),
        city_names.ne(city_names.str.upper()).sum(),
        city_names.str.strip().nunique(),
        city_names.str.strip().str.upper().nunique()
    ]
})

city_consistency

                                   Fields  Value
0                       Unique City Names   8955
1  Names with Leading/Trailing Whitespace      0
2  Names with Inconsistent Capitalization  20440
3  Unique Names After Trimming Whitespace   8955
4   Unique Names After Standardizing Case   7297

In [123]:
city_case_variations = (
    df["ship-city"]
    .dropna()
    .groupby(df["ship-city"].dropna().str.strip().str.upper())
    .agg(
        Original_Variations="nunique",
        Variations=lambda x: sorted(x.unique().tolist())
    )
    .query("Original_Variations > 1")
    .sort_values("Original_Variations", ascending=False)
)

city_case_variations.head(20)

,Original_Variations,Variations
ship-city,,
NEW DELHI,8,"[NEW DELHI, NEW DELHi, NEW Delhi, New DELHI, N..."
GREATER NOIDA WEST,8,"[GREATER NOIDA WEST, GREATER NOIDA West, GREAT..."
NAVI MUMBAI,7,"[NAVI MUMBAI, NAVI MUMBAi, NAVI mumbai, Navi M..."
BANGALORE,6,"[BANGALORE, BAngalore, BangaLore, Bangalore, b..."
THANE WEST,6,"[THANE WEST, THANE West, THANE west, Thane Wes..."
DEHRADUN,5,"[DEHRADUN, DEHRADUn, DehraDun, Dehradun, dehra..."
MIRA ROAD EAST,5,"[MIRA ROAD EAST, Mira Road East, Mira Road eas..."
RANCHI,5,"[RANCHI, RANCHi, RANChi, Ranchi, ranchi]"
PORT BLAIR,5,"[PORT BLAIR, Port Blair, Port blair, port Blai..."
MUMBAI,5,"[MUMBAI, MUMBAi, MUMBai, Mumbai, mumbai]"
KALYAN EAST,5,"[KALYAN EAST, KALYAN East, KALYAN east, Kalyan..."
KALYAN WEST,5,"[KALYAN WEST, KALYAN West, KALYAN west, Kalyan..."
GREATER NOIDA,5,"[GREATER NOIDA, Greater NOIDA, Greater Noida, ..."
EAST DELHI,5,"[EAST DELHI, East DELHI, East Delhi, East delh..."
AMBALA CANTT,5,"[AMBALA CANTT, AMBALA Cantt, AMBALA cantt, Amb..."
VIRAR WEST,5,"[VIRAR WEST, VIRAR West, VIRAR west, Virar Wes..."
VASAI WEST,4,"[VASAI WEST, VASAI West, VASAI west, Vasai west]"
VASCO DA GAMA,4,"[VASCO DA GAMA, Vasco Da Gama, Vasco da Gama, ..."
THANE EAST,4,"[THANE EAST, THANE east, Thane East, Thane east]"
NOIDA EXTENSION,4,"[NOIDA Extension, NOIDA extension, Noida Exten..."

## 28. Shipping State Inspection

This section examines the `ship-state` column's data type, completeness, and frequently occurring values to identify potential inconsistencies in state names and their representation.

In [124]:
ship_state_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values"
    ],
    "Value": [
        "ship-state",
        str(df["ship-state"].dtype),
        len(df["ship-state"]),
        df["ship-state"].isna().sum(),
        f"{df['ship-state'].isna().mean() * 100:.2f}%",
        df["ship-state"].nunique()
    ]
})

ship_state_inspection

               Fields       Value
0         Column Name  ship-state
1           Data Type         str
2          Total Rows      128975
3      Missing Values          33
4  Missing Percentage       0.03%
5       Unique Values          69

In [125]:
df["ship-state"].value_counts(dropna=False).head(20).to_frame("Count")

                Count
ship-state
MAHARASHTRA     22260
KARNATAKA       17326
TAMIL NADU      11483
TELANGANA       11330
UTTAR PRADESH   10638
DELHI            6782
KERALA           6585
WEST BENGAL      5963
ANDHRA PRADESH   5430
Gujarat          4489
HARYANA          4415
RAJASTHAN        2650
MADHYA PRADESH   2529
ODISHA           2115
BIHAR            2086
PUNJAB           1869
ASSAM            1663
UTTARAKHAND      1553
JHARKHAND        1456
GOA              1102

In [126]:
state_names = df["ship-state"].dropna()

state_consistency = pd.DataFrame({
    "Fields": [
        "Unique State Names",
        "Names with Leading/Trailing Whitespace",
        "Names with Inconsistent Capitalization",
        "Unique Names After Trimming Whitespace",
        "Unique Names After Standardizing Case"
    ],
    "Value": [
        state_names.nunique(),
        state_names.ne(state_names.str.strip()).sum(),
        state_names.ne(state_names.str.upper()).sum(),
        state_names.str.strip().nunique(),
        state_names.str.strip().str.upper().nunique()
    ]
})

state_consistency

                                   Fields  Value
0                      Unique State Names     69
1  Names with Leading/Trailing Whitespace    257
2  Names with Inconsistent Capitalization   4988
3  Unique Names After Trimming Whitespace     69
4   Unique Names After Standardizing Case     47

In [127]:
state_case_variations = (
    df["ship-state"]
    .dropna()
    .groupby(
        df["ship-state"].dropna().str.strip().str.upper()
    )
    .agg(
        Original_Variations="nunique",
        Variations=lambda x: sorted(x.unique().tolist())
    )
    .query("Original_Variations > 1")
    .sort_values("Original_Variations", ascending=False)
)

state_case_variations

,Original_Variations,Variations
ship-state,,
ARUNACHAL PRADESH,3,"[ARUNACHAL PRADESH, Arunachal Pradesh, Arunach..."
BIHAR,3,"[BIHAR, Bihar, bihar]"
DELHI,3,"[DELHI, Delhi, delhi]"
GOA,3,"[GOA, Goa, goa]"
PUNJAB,3,"[PUNJAB, Punjab, punjab]"
RAJASTHAN,3,"[RAJASTHAN, Rajasthan, rajasthan]"
CHANDIGARH,2,"[CHANDIGARH, Chandigarh]"
MANIPUR,2,"[MANIPUR, Manipur]"
MIZORAM,2,"[MIZORAM, Mizoram]"
MEGHALAYA,2,"[MEGHALAYA, Meghalaya]"
NAGALAND,2,"[NAGALAND, Nagaland]"
ODISHA,2,"[ODISHA, Odisha]"
PUDUCHERRY,2,"[PUDUCHERRY, Puducherry]"
ORISSA,2,"[Orissa, orissa]"
RAJSTHAN,2,"[Rajsthan, rajsthan]"
SIKKIM,2,"[SIKKIM, Sikkim]"

In [128]:
df["ship-state"].value_counts(dropna=False).to_frame("Count")

               Count
ship-state
MAHARASHTRA    22260
KARNATAKA      17326
TAMIL NADU     11483
TELANGANA      11330
UTTAR PRADESH  10638
...              ...
Nagaland           1
bihar              1
Mizoram            1
rajsthan           1
Rajsthan           1

[70 rows x 1 columns]

## 29. Shipping Postal Code Inspection

This section examines the `ship-postal-code` column's data type, completeness, and frequently occurring values to assess how shipping postal codes are represented in the dataset.

In [129]:
postal_code_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values"
    ],
    "Value": [
        "ship-postal-code",
        str(df["ship-postal-code"].dtype),
        len(df["ship-postal-code"]),
        df["ship-postal-code"].isna().sum(),
        f"{df['ship-postal-code'].isna().mean() * 100:.2f}%",
        df["ship-postal-code"].nunique()
    ]
})

postal_code_inspection

               Fields             Value
0         Column Name  ship-postal-code
1           Data Type           float64
2          Total Rows            128975
3      Missing Values                33
4  Missing Percentage             0.03%
5       Unique Values              9459

In [130]:
df["ship-postal-code"].value_counts(dropna=False).head(20).to_frame("Count")

                  Count
ship-postal-code
201301.0           1006
122001.0            688
560037.0            632
560068.0            619
560076.0            581
560043.0            500
401107.0            493
500072.0            490
560100.0            489
560066.0            464
560078.0            447
500049.0            437
248001.0            432
500090.0            430
411057.0            428
500084.0            415
560102.0            400
560064.0            385
500089.0            372
411014.0            365

## 30. Shipping Country Inspection

This section examines the `ship-country` column's data type, completeness, and distinct values to understand how shipping destinations are represented by country codes.

In [131]:
ship_country_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Countries"
    ],
    "Value": [
        "ship-country",
        df["ship-country"].dtype,
        len(df),
        df["ship-country"].isna().sum(),
        df["ship-country"].nunique()
    ]
})

ship_country_inspection

             Fields         Value
0       Column Name  ship-country
1         Data Type           str
2        Total Rows        128975
3    Missing Values            33
4  Unique Countries             1

In [132]:
df["ship-country"].value_counts(dropna=False).to_frame("Count")

               Count
ship-country
IN            128942
NaN               33

## 31. Promotion IDs Inspection

This section examines the `promotion-ids` column's data type, completeness, and frequently occurring values to understand how promotional identifiers are recorded in the dataset.

In [133]:
promotion_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values"
    ],
    "Value": [
        "promotion-ids",
        df["promotion-ids"].dtype,
        len(df),
        df["promotion-ids"].isna().sum(),
        f"{df['promotion-ids'].isna().mean() * 100:.2f}%",
        df["promotion-ids"].nunique()
    ]
})

promotion_inspection

               Fields          Value
0         Column Name  promotion-ids
1           Data Type            str
2          Total Rows         128975
3      Missing Values          49153
4  Missing Percentage         38.11%
5       Unique Values           5787

In [134]:
df["promotion-ids"].value_counts(dropna=False).head(10).to_frame("Count")

                                                    Count
promotion-ids
NaN                                                 49153
IN Core Free Shipping 2015/04/08 23-48-5-108        46100
Duplicated A12RHGVGRWOT3S 1560498941486               489
Amazon PLCC Free-Financing Universal Merchant A...    458
Duplicated AYTJSBA8ZOP16 1567159860988                433
Amazon PLCC Free-Financing Universal Merchant A...    316
Amazon PLCC Free-Financing Universal Merchant A...    305
Amazon PLCC Free-Financing Universal Merchant A...    230
Amazon PLCC Free-Financing Universal Merchant A...    206
Amazon PLCC Free-Financing Universal Merchant A...    201

## 32. Fulfilled By Column Inspection

This section examines the `fulfilled-by` column's data type, completeness, and distinct values to understand how the fulfillment provider is recorded in the dataset.

In [135]:
fulfilled_by_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values"
    ],
    "Value": [
        "fulfilled-by",
        df["fulfilled-by"].dtype,
        len(df),
        df["fulfilled-by"].isna().sum(),
        f"{df['fulfilled-by'].isna().mean() * 100:.2f}%",
        df["fulfilled-by"].nunique()
    ]
})

fulfilled_by_inspection

               Fields         Value
0         Column Name  fulfilled-by
1           Data Type           str
2          Total Rows        128975
3      Missing Values         89698
4  Missing Percentage        69.55%
5       Unique Values             1

In [136]:
df["fulfilled-by"].value_counts(dropna=False).to_frame("Count")

              Count
fulfilled-by
NaN           89698
Easy Ship     39277

## 33. Unnamed Column Inspection

This section examines the `Unnamed: 22` column's data type, completeness, and distinct values to determine whether it contains meaningful information or an unintended artifact from the original dataset.

In [137]:
unnamed_column_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Missing Percentage",
        "Unique Values"
    ],
    "Value": [
        "Unnamed: 22",
        df["Unnamed: 22"].dtype,
        len(df),
        df["Unnamed: 22"].isna().sum(),
        f"{df['Unnamed: 22'].isna().mean() * 100:.2f}%",
        df["Unnamed: 22"].nunique()
    ]
})

unnamed_column_inspection

               Fields        Value
0         Column Name  Unnamed: 22
1           Data Type       object
2          Total Rows       128975
3      Missing Values        49050
4  Missing Percentage       38.03%
5       Unique Values            1

In [138]:
df["Unnamed: 22"].value_counts(dropna=False).to_frame("Count")

             Count
Unnamed: 22
False        79925
NaN          49050

## 34. B2B Column Inspection

This section examines the `B2B` column's data type, completeness, and distinct values to understand how business-to-business transactions are identified in the dataset.

In [139]:
b2b_inspection = pd.DataFrame({
    "Fields": [
        "Column Name",
        "Data Type",
        "Total Rows",
        "Missing Values",
        "Unique Values"
    ],
    "Value": [
        "B2B",
        df["B2B"].dtype,
        len(df),
        df["B2B"].isna().sum(),
        df["B2B"].nunique()
    ]
})

b2b_inspection

           Fields   Value
0     Column Name     B2B
1       Data Type    bool
2      Total Rows  128975
3  Missing Values       0
4   Unique Values       2

In [140]:
df["B2B"].value_counts(dropna=False).to_frame("Count")

        Count
B2B
False  128104
True      871

## Key Findings and Conclusion

### Key Findings

The data quality assessment identified the following observations:

* **Dataset size:** The dataset contains 128,975 rows and 24 columns.
* **Duplicate records:** No exact duplicate rows were identified. However, 8,597 repeated `Order ID` values were found, which may represent multiple line items associated with the same order.
* **Missing values:** The `fulfilled-by` column has 69.55% missing values, followed by `promotion-ids` at 38.11% and `Unnamed: 22` at 38.03%. The `Amount` and `currency` columns each have 6.04% missing values.
* **Data types:** The `Date` column is stored as text, while `ship-postal-code` is represented as a floating-point value. These columns require further consideration during data preparation.
* **Categorical inconsistencies:** The `ship-city` and `ship-state` columns contain inconsistent capitalization. The state column also includes potential spelling variations and alternative names.
* **Amount values:** The `Amount` column contains 2,343 zero values. These records require contextual investigation before deciding how to handle them.
* **Unnecessary columns:** The `index`, `currency`, `sku`, `asin`, `ship-city`, `ship-postal-code`, `promotion-ids`, and `Unnamed: 22` columns have been identified for removal during the cleaning stage.
* **Business-to-business transactions:** The `B2B` column contains 871 records marked as business-to-business transactions, making it a potentially useful field for further analysis.

### Conclusion

The assessment identified missing values, repeated order identifiers, categorical inconsistencies, unusual amount values, and columns that may not contribute to the planned analysis. These findings will guide the data cleaning and preparation process in the next stage of the RetailPulse project.

No data transformations have been performed in this notebook. The raw dataset remains unchanged, preserving it as the source for subsequent processing.